### ISSUE TITLE
request for an add-on for app

### ISSUE THREAD

**Issue by fvhuizen** [martijnpoppen/magic.home.wifi#1]
Can the app be extended with the use of single white strips?

**Comment by jghaanstra** [comment]
Could you let me know which controller you have connected. If it's one of the already supported controllers (RGB or RGBW) it should already work using the dim action cards I think. If it's a new controller I might need to know the controller identifier which needs to be obtained through command line.

**Comment by fvhuizen** [comment]
![img_8138](https://user-images.githubusercontent.com/25953849/48224147-372d0980-e399-11e8-890a-df42fa035428.jpeg)
Thx for you're prompt response, attached a photo i hope this suites you to fix it

**Comment by fvhuizen** [comment]
here i have a RGBW strip attached on the other controller just a W strip

**Comment by jghaanstra** [comment]
That controller does not at all look like a regular Magic Home controller but since it works with the Magic Home app it must be using the same protocol. Can it be controlled trough Homey using the RGBW LED strip?

**Comment by fvhuizen** [comment]
Yes thats correct when using RGBW it's working on Homey as well.
Further details about the controller by this link.
https://nl.aliexpress.com/item/DC12-24V-4A-5CH-RGB-WW-CW-LED-WIFI-Controller-IOS-Android-Smart-Link-Timer-Muziek/32850751889.html?spm=a2g0s.9042311.0.0.3da24c4dx44dNB

**Comment by jghaanstra** [comment]
And have you tried using the dim and /  or temperature card to see if at least that works. And if you know how to do a CLI install you can try and run it from command line to see what comes up when trying to control it.

**Comment by fvhuizen** [comment]
When the device is installed on Homey i can't change settings whatever i try. But it sees the controller and it's dimmed when it's off and black when it's on. I know how to install app's with CLI but maybe you can help me with the commands to run it on the command line

**Comment by jghaanstra** [comment]
the command is `athom app run` ... than just try to control it with a flow where you change the dim brightness and see if the console shows any info.

**Comment by fvhuizen** [comment]
okay i will test it tomorrow and keep you posted

**Comment by jghaanstra** [comment]
Any news on this @fvhuizen or can I close the issue?

**Comment by fvhuizen** [comment]
i didn't manage to control it via the console, so you can close the issue, i ordered two single color controllers to test
