### ISSUE TITLE
Multiple pings

### ISSUE THREAD

**Issue by AdyRock** [martijnpoppen/magic.home.wifi#10]
I have just been look at the code and I see the ping routine is in the device. That routine seems to update every device but as it runs in the device it will mean there could be multiple routines running, one for each device added to Homey.
I think that code should be moved to the app.

Also when a device is deleted, this.pollingInterval is cleared but this.pingInterval) isn't so it will be left running.

**Comment by martijnpoppen** [comment]
Will fix :)

**Comment by martijnpoppen** [comment]
Fixed in 3.3.11
