### ISSUE TITLE
Permanently Reboot from the WiFi Controller

### ISSUE THREAD

**Issue by ghost** [martijnpoppen/magic.home.wifi#11]
hallo martijnpoppen,

i have seen that the magic.home.wifi Controller reboot permanently all 1 Minutes and 7 seconds. 
But when the app is open, the magic.home.wifi controller is permanently in the network and it gives no more disconnects.

Is the app closed, than the controller reboot again every >1 minute.
Gives it a way to prevent the permanently reboot of the controller if the app are close and not only if the app are open?

With best regards
Athraell

**Comment by martijnpoppen** [comment]
Hey @Athraell ,
Sorry totally missed this issue.
I just took over the app around the time you made the issue ;)

I think when you give it a static IP it should work.

Kind Regards
Martijn
