### ISSUE TITLE
Add please support for LED RGBWW

### ISSUE THREAD

**Issue by volodeev** [martijnpoppen/magic.home.wifi#4]
v1.1.0
Supports ON and OFF only. 
Not supported: 
1) Level is cool white/warm white; 
2) Color change RGB.
![rgbww](https://user-images.githubusercontent.com/46497923/50850767-a4aae580-139c-11e9-80bf-0615d71d3042.jpg)

https://nl.aliexpress.com/item/DC12-24V-4A-5CH-RGB-WW-CW-LED-WIFI-Controller-IOS-Android-Smart-Link-Timer-Muziek/32850751889.html?spm=a2g0s.9042311.0.0.3da24c4dx44dNB

**Comment by jghaanstra** [comment]
I may have found the issue and habe pushed a new release to Github. Do you know how to do a CLI install to test if it is working correctly now?

**Comment by volodeev** [comment]
> I may have found the issue and habe pushed a new release to Github. Do you know how to do a CLI install to test if it is working correctly now?

I will try to install CLI, if I fail, I will ask you. I need 1-2 days to check. I will inform you about the results

**Comment by volodeev** [comment]
> I may have found the issue and habe pushed a new release to Github. Do you know how to do a CLI install to test if it is working correctly now?

v1.1.1 doesn't work either.
![app_v1 1 1](https://user-images.githubusercontent.com/46497923/50918068-06348800-1461-11e9-809f-279cd3df3d44.jpg)
The controller is defined as RGBWW!
![controller](https://user-images.githubusercontent.com/46497923/50918016-e00ee800-1460-11e9-8c0e-6a8faaa6c21a.jpg)

The application magic.home.wifi (Athom Homey) does not change the modes, but only reads. If change the color and temperature through the application Magic Home WiFi ([Apple](https://itunes.apple.com/ru/app/magic-home-wifi/id944574066?mt=8)), then in magic.home.wifi (Athom Homey) the changes are visible.

**Comment by jghaanstra** [comment]
RBGWW is just a type-o, it does not have any other effect on functionality.

Since I dont own a RGBWW controller there is no way for me to test what is going on. I have pushed a new version to Github with extra logging. Please run this from the command line (`athom app run`), try and change the color or temperature and copy and paste the output from the console here.

**Comment by volodeev** [comment]
> RBGWW is just a type-o, it does not have any other effect on functionality.
> 
> Since I dont own a RGBWW controller there is no way for me to test what is going on. I have pushed a new version to Github with extra logging. Please run this from the command line (`athom app run`), try and change the color or temperature and copy and paste the output from the console here.
---------------------------------------------------
2019-01-11 10:14:27 [log] [MagicHomeApp] Initializing Magic Home app ...
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in hue/saturation
{ light_hue: 0.97 }
change in hue/saturation
{ light_hue: 0.96 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in hue/saturation
{ light_hue: 0.96 }
change in hue/saturation
{ light_hue: 0.98 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in hue/saturation
{ light_hue: 0.4 }
change in hue/saturation
{ light_saturation: 0 }
change in hue/saturation
{ light_saturation: 0.18 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in temperature
change in temperature
change in temperature
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in temperature
change in temperature
change in temperature
change in temperature
change in temperature
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in temperature
change in temperature
change in temperature
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }
change in hue/saturation
{ light_hue: 0.94 }
{ on: true,
  mode: 'warm_white',
  speed: 36.66666666666667,
  color: { red: 0, green: 255, blue: 0 },
  warm_white_percent: 50.19607843137255 }

**Comment by jghaanstra** [comment]
Well, there is nothing strange in there. So I really dont know why it aint working. Without an actual RGBWW controller and LED strip it's impossible for me to troubleshoot.

I'm using [this](https://github.com/jangxx/node-magichome#readme) node library to control the Magic Home controllers. If you have any technical knowledge yourself you should check if you can use the `setColor()` function. This what is used inside my application to change the color of the leds.

**Comment by jghaanstra** [comment]
I have just uploaded a new version. I dont think it will solve your issue but you could try it out. What would help me is post a screenshot of the Magic Home smartphone app. I'd like to see what settings are available for a RGBWW controller.

**Comment by volodeev** [comment]
> I have just uploaded a new version. I dont think it will solve your issue but you could try it out. What would help me is post a screenshot of the Magic Home smartphone app. I'd like to see what settings are available for a RGBWW controller.

![colors](https://user-images.githubusercontent.com/46497923/51405829-38d53380-1b79-11e9-8a20-d1a22141afab.jpg) ![cct](https://user-images.githubusercontent.com/46497923/51405823-35da4300-1b79-11e9-8a6a-d0d21b45eccd.jpg)

**Comment by jghaanstra** [comment]
Hmm, seems you are using a different app to control your device. This does not give me much info either, I'm afraid I wont be able to solve this without actually having this controller and RGBWW LED strip. Sorry.

**Comment by volodeev** [comment]
Maybe it will help you. If controlled via the application Magic Home WiFi (Apple) from the phone, the changes are visible in the device Athom Homey.

**Comment by jghaanstra** [comment]
Nope, does not really help. It looks like the magic-home node library currently does not support controlling your controller (or perhaps even all RGBWW Magic Home controllers). It seems different commands are needed to set the color and color temperature for these devices. This needs further testing but as mentioned without this device and a RGBWW LED strip there is nothing I can do.

I have uploaded a new version to Github recently which is also pending the app store. When (re-)pairing it will show the model identifier in the name. It would help me if you could supply me with the model shown so I can identify this in my app.

**Comment by volodeev** [comment]
> Nope, does not really help. It looks like the magic-home node library currently does not support controlling your controller (or perhaps even all RGBWW Magic Home controllers). It seems different commands are needed to set the color and color temperature for these devices. This needs further testing but as mentioned without this device and a RGBWW LED strip there is nothing I can do.
> 
> I have uploaded a new version to Github recently which is also pending the app store. When (re-)pairing it will show the model identifier in the name. It would help me if you could supply me with the model shown so I can identify this in my app.

RGBWW controller HF-LPB100-ZJ200 (192.168.0.100)

**Comment by jghaanstra** [comment]
Ok, I cant do much for you anymore but there is still a lot you can do yourself if you really would like to see support. You should start by reading [this](https://github.com/jangxx/node-magichome/issues/4#issuecomment-466807252) response in the magic-home nodejs library.

You could install the magic-home node js library locally and make a test script setting the `log_all_received` option to `true` and run the `queryState` function. That might give more details of the type. All is described in the linked response and readme of the magic-home nodejs extension. If that fails you could also try the Python library and see if that gets you any further. If it does you could report your findings in the nodejs magic-home library and see if support can be created.

Not much more I can do myself.

**Comment by jghaanstra** [comment]
I haven't heard back and someone else on Slack told me he has two working units of this type so I'm closing this issue.
