### ISSUE TITLE
Add please support for Magic Home LED SPI Controller Addressable Pixel

### ISSUE THREAD

**Issue by edsallo** [martijnpoppen/magic.home.wifi#5]
https://ru.aliexpress.com/item/DC5V-Magic-Home-LED-SPI-Controller-Addressable-Pixel-DC12-24V-Mini-WiFi-Controller-For-WS2811-SK6812/32959345574.html?spm=a2g0v.10010108.1000016.1.575d25dfK8ekWv&isOrigTitle=true

**Comment by jghaanstra** [comment]
Have you tried pairing it with the Magic Home Homey app already? If so, what was the result?

I dont think the nodejs library I'm using to control the Magic Home controllers with Homey has implemented support for this. So it will need to be revered engineered. So it may take a while before I can add support for this, if it ever comes. I dont own the device myself so I cant really test or help develop support for it.

**Comment by edsallo** [comment]
I'm just going to buy it. But since the management of addressable LED strips is completely different, I think the plugin cannot work with it.

**Comment by jghaanstra** [comment]
Stuff like setting all leds to the same color and setting the LED strip to display a predefined effect may still work. Setting individual leds will indeed not work. Let me know what happens when you try to pair it.

**Comment by jghaanstra** [comment]
@edsallo I ordered a Magic Home SPI addressable controller as well together with a short WS2812b LED strip but I was unable to actually control the LED strip. I can see the settings in the controller are updated but the LED strip does not respond to any changes. According to the description of the Magic Home SPI addressable controller this LED strip type should work. Where you able to control the LED's (at least through the Magic Home app)?

**Comment by edsallo** [comment]
I do not have SPI version. I was going to buy.
I heard that this is a controller firmware issue. They are programmed into Tasmota and the controller starts working.

**Comment by jghaanstra** [comment]
Where have you read this, I see no such info in the Tasmota repository.

**Comment by imbaimbaimba** [comment]
Did something like this ever get working? I've been looking at this: https://www.youtube.com/watch?v=tW7HVPv1TcQ
Looks really cool. Would love to be able to save effects and integrate into Homey.

**Comment by jghaanstra** [comment]
I'm awaiting the delivery of a new addressable controller on 5V. I previously ordered one of 12V-24V and that does not seem to work with my ws2812b LED strips. 

After I receive it I can start testing to see what is possible. Starting pre defined effects should not be hard to add to my app but there are over 300 of those. It's gonna be a hell of a job getting them added to my Homey app.

The configuration app for custom effects shown in the video is new to me. I would have to look into that and see if I can find it, reverse engineer it and come up with a way to use it in a Homey flow. All that is less likely.

**Comment by jghaanstra** [comment]
I have tried 2 SPI addressable controllers (one for 5V and one for 12-24V) with  two different WS2812b LED strips but was unable to get it to work. If anyone has more info on how to get this controller to work and actually be able to control the lights, please let me know. For now I'm closing this issue.

**Comment by directman66** [comment]
similar situation does not work even through the native application

**Comment by phixion** [comment]
@jghaanstra did you make any progress? my 5V controller dont even turn on when connected to a 5V powersupply

PS: with esphome you can use every magichome rgb+IR controller as a adressable led controller, just utilize the IR pin as the datapin

**Comment by jghaanstra** [comment]
Nope, but I did not put any effort into it anymore after this experiment.

Perhaps when I have time I can play some with ESPHome or Tasmota and see if I can get it to work as addressable LED controller. But that would be unrelated to adding support within my Homey app for these devices.

**Comment by phixion** [comment]
It seems to be flashable but controlling the leds is only possible through their weird MCU so there's not much one can do.

**Comment by jghaanstra** [comment]
Yeah, I googled a bit on Tasmota and ESPHome but no one seems to have got this working properly. Also tried to use the Magic Home app to see if there are any improvements. I cant get anything out of my 5V and 12V Magic Home SPI controllers. I have given up on these devices.

Might try to turn an regular RGBW Magic Home controller with IR into a addressable controller somewhere in the future.

**Comment by aenertia** [comment]
Tasmota recently added Tuya slave protocol support. Which MAY be worth investigating; you still need to go through the pain of getting the ESP02 chip flashed; which even with a bunch of what appeared correct pullups and wiring to a sacrificial board I could not get to enter flash mode.

**Comment by jghaanstra** [comment]
Could be this is coming after all. Depends on how this integration goes:

https://github.com/jangxx/node-magichome/pull/26

**Comment by jghaanstra** [comment]
Support for this controller is added including setting one of the 300 pre-configured effects with release 3.0.0.
